AWSTemplateFormatVersion: '2010-09-09'
Description: Create a public EC2 instance using an existing Security Group and Subnet

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in the existing VPC

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Existing Security Group with port 80 open

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Linux 2 AMI

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: CloudFormation-Web-Server
