AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create two EC2 instances in different VPCs and public subnets
  using one CloudFormation stack

Parameters:

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair
    Default: keren-key

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in the existing VPC
    Default: subnet-01b2d1ae1f6351dff

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Existing Security Group with port 80 open
    Default: sg-05dd3efe190ff30ef

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Linux 2 AMI
    Default: ami-0b6c6ebed2801a5cb

Resources:

  EC2InstanceVpcA:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-07ff62358b87c7116
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetVpcA
          GroupSet:
            - !Ref SecurityGroupVpcA
          AssociatePublicIpAddress: true

  EC2InstanceVpcB:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: CloudFormation-Web-Server


