AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create two EC2 instances in different VPCs and public subnets
  using one CloudFormation stack

Parameters:

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  SubnetVpcA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-025b1d1f3a33559bb
    Description: Public subnet in VPC A

  SecurityGroupVpcA:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-05dd3efe190ff30ef
    Description: Security group in VPC A

  SubnetVpcB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-04c5dc9a3aca59e0e
    Description: Public subnet in VPC B

  SecurityGroupVpcB:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0b0585d99610bb23c
    Description: Security group in VPC B

Resources:

  EC2InstanceVpcA:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-07ff62358b87c7116
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetVpcA
          GroupSet:
            - !Ref SecurityGroupVpcA
          AssociatePublicIpAddress: true

  EC2InstanceVpcB:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-07ff62358b87c7116
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetVpcB
          GroupSet:
            - !Ref SecurityGroupVpcB
          AssociatePublicIpAddress: true
